### ISSUE TITLE
Model weight availability

### ISSUE THREAD

**Issue by ElianBelot** [hanrthu/CoPRA#1]
Hi there! Thanks for the great work.
When can we expect the model weights to be made available?

**Comment by hanrthu** [comment]
Hi！Thank you for your interest in our work. The model and weights are expected to be available before 15th, December, together with the PRA310, PRA201, and PRI30k datasets.

**Comment by hanrthu** [comment]
Sorry for the delay. This is because CoPRA has been accepted by AAAI 2025 and we are preparing for the camera ready version these days. The datasets and weights will be uploaded in this week.

**Comment by hanrthu** [comment]
Hi Elian, CoPRA is now publicly available! Hope you have fun using it. If you have any further questions, please let me know
